### ISSUE TITLE
Tracking: New architecture + 1.0 release

### ISSUE THREAD

**Issue by nx10** [childmindresearch/styx#45]
### Description

This issue is tracking the progress of the new architecture. Once it is established we will release 1.0 of styx and shortly after the first pypi version of niwrap.

This new architecture will mak it easier to add new features independently of boutiques, perform optimizations, and add new input formats and targets.

### Tasks

- [x] IR data model
- [ ] Frontends (input formats)
  - [x] Boutiques
- [ ] Backends (code generation / targets)
  - [ ] Python (in progress)
  - [ ] Boutiques
